app = 'zoe'
primary_region = 'ams'

[build]
  dockerfile = 'fly.Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  ZOE_EVENTS_FILE = '/data/events'
  ZOE_MIN_REPORT_INTERVAL = '30s'
  ZOE_BLOCK_SIZE = '10000'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = "1gb"

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 1000000
    soft_limit = 800000

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory = 512
