# fly.toml app configuration file generated for swi-zoe on 2024-02-16T09:59:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swi-zoe'
primary_region = 'ams'

[build]
  dockerfile = 'fly.Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  ZOE_BLOCK_SIZE = '10000'
  ZOE_EVENTS_FILE = '/data/events'
  ZOE_MIN_REPORT_INTERVAL = '10s'
  ZOE_WORKER_POOL_SIZE = '8'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 1000000
    soft_limit = 800000

[[vm]]
  size = 'shared-cpu-1x'
