# fly.toml app configuration file generated for lstn on 2024-02-03T13:10:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lstn'
primary_region = 'ams'

[build]
  dockerfile = 'fly.Dockerfile'

[deploy]
  strategy = 'immediate'

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
