# fly.toml app configuration file generated for lstn-spring-surf-504 on 2024-02-06T04:35:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lstn-spring-surf-504'
primary_region = 'ams'

[build]
  dockerfile = 'fly.Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  LSTN_EVENTS_FILE = '/data/events'
  LSTN_MIN_REPORT_INTERVAL = '30s'

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 200000
    soft_limit = 100000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
