name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Fly
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly
      id: deploy
      run: |
        flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Post Deploy
      run: chmod +x post-deploy.sh && ./post-deploy.sh
      env:
        RECORD_NAME: lstn.swissinfo.ch
        AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
