name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Fly
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly
      id: deploy
      run: |
        flyctl deploy --remote-only
        IPS_LIST=$(flyctl ips list)
        IPV6=$(echo "$IPS_LIST" | awk '/v6/{print $2}')
        IPV4=$(echo "$IPS_LIST" | awk '/v4/{print $2}')
        echo "IPV6=${IPV6}" >> $GITHUB_ENV
        echo "IPV4=${IPV4}" >> $GITHUB_ENV
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


    - name: Update AWS Resources
      run: |
        chmod +x update-aws.sh
        ./update-aws.sh \
            lstn.swissinfo.ch \
            --ipv6 $IPV6 \
            --ipv4 $IPV4
      env:
        RECORD_NAME: lstn.swissinfo.ch
        AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
        IPV6: ${{ env.IPV6 }}
        IPV4: ${{ env.IPV4 }}
