name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Fly
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly
      id: deploy
      run: |
        flyctl deploy --remote-only
        echo "::set-output name=ipv6::$(flyctl info --format "{{.IPAddresses.IPv6}}")"
        echo "::set-output name=ipv4::$(flyctl info --format "{{.IPAddresses.IPv4}}")"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Update AWS Resources
      run: |
        chmod +x update-aws.sh
        ./update-aws.sh lstn.swissinfo.ch \
            --ipv6 ${{ steps.deploy.outputs.ipv6 }} \
            --ipv4 ${{ steps.deploy.outputs.ipv4 }} \
            --hosted-zone-id ${{ secrets.HOSTED_ZONE_ID }}
